[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
